sudo: required
services:
    - docker

language: go

go:
  - "1.11.x"

env:
    global:
        - SHA=$(git rev-parse HEAD)

before_install:
    - docker build -t 0xsegfault/client-test -f ./client/Dockerfile.dev ./client

script:
    - docker run 0xsegfault/client-test npm run lint

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - ./api/scripts/install.sh
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o api/bin/api api/main.go

deploy:
    provider: script
    script: bash ./deploy.sh
    on:
        branch: master