version: "3"

services:

  zookeeper:
    image: hyperledger/fabric-zookeeper:0.4.14
    restart: always
    ports:
      - '2181'
      - '2888'
      - '3888'
    networks:
      - fusion
  
  kafka:
    image: hyperledger/fabric-kafka:0.4.14
    restart: always
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181,zoo2:2181,zoo3:2181
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - fusion
