Capabilities:
  Global: &ChannelCapabilities
    V1_3: true
    V1_1: true
  
  Orderer: &OrdererCapabilities
    V1_1: true
  
  Application: &ApplicationCapabilities
    V1_3: true
    V1_2: true
    V1_1: true
  
Organizations:

  - &OrdererOrg
    Name: OrdererMSP
    ID: OrdererMSP
    AdminPrincipal: Role.ADMIN
    MSPDir: crypto-config/ordererOrganizations/segfault.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
  
  - &Org1
    Name: Org1MSP
    ID: Org1MSP
    MSPDir: crypto-config/peerOrganizations/Org1.com/msp
    AdminPrincipal: Role.ADMIN
    AnchorPeers:
      - Host: peer0.Org1.com
        Port: 7051
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org1MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org1MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org1MSP.admin')"
  
  - &Org2
    Name: Org2MSP
    ID: Org2MSP
    MSPDir: crypto-config/peerOrganizations/Org2.com/msp
    AdminPrincipal: Role.ADMIN
    AnchorPeers:
      - Host: peer0.Org2.com
        Port: 7051
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org2MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org2MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org2MSP.admin')"
  
  - &Org3
    Name: Org3MSP
    ID: Org3MSP
    MSPDir: crypto-config/peerOrganizations/Org3.com/msp
    AdminPrincipal: Role.ADMIN
    AnchorPeers:
      - Host: peer0.Org3.com
        Port: 7051
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org3MSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('Org3MSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('Org3MSP.admin')"

Orderer: &OrdererDefaults
  OrdererType: kafka

  Addresses:
    - orderer1-service:7050
    - orderer2-service:7050
    - orderer3-service:7050
  
  BatchTimeout: 50ms
  BatchSize:
    MaxMessageCount: 1
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB

  MaxChannels: 0

  Kafka:
    Brokers:
      - kafka1-service:9092
      - kafka2-service:9092
      - kafka3-service:9092
      - kafka4-service:9092
  
  Organizations:

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  
  Capabilities:
    <<: *OrdererCapabilities


Application: &ApplicationDefaults
  Organizations:

  Capabilities:
    <<: *ApplicationCapabilities

Profiles:
  OrdererGenesis:
    Capabilities:
      <<: *ChannelCapabilities
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *ApplicationCapabilities
    Consortiums:
      MainConsortium:
        Organizations:
          - *OrdererOrg
          - *Org1
          - *Org2
          - *Org3
  
  MainChannel:
    Consortium: MainConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Org1
        - *Org2
        - *Org3
      Capabilities:
        <<: *ApplicationCapabilities
