Profiles:

    SEGFAULTOrdererGenesis:
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SEGFAULT:
                Organizations:
                    - *Org1
                    - *Org2
                    - *Org3

    MainChannel:
        Consortium: SEGFAULT
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2
                - *Org3
            Capabilities:
                <<: *ApplicationCapabilities

Organizations:

    - &OrdererOrg
        Name: OrdererMSP
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/segfault.com/msp

    - &Org1
        Name: Org1MSP
        ID: Org1MSP
        MSPDir: crypto-config/peerOrganizations/Org1.com/msp

        AnchorPeers:
            - Host: peer0.Org1.com
              Port: 7051

    - &Org2
        Name: Org2MSP
        ID: Org2MSP
        MSPDir: crypto-config/peerOrganizations/Org2.com/msp

        AnchorPeers:
            - Host: peer0.Org2.com
              Port: 7051

    - &Org3
        Name: Org3MSP
        ID: Org3MSP
        MSPDir: crypto-config/peerOrganizations/Org3.com/msp

        AnchorPeers:
            - Host: peer0.Org3.com
              Port: 7051


Orderer: &OrdererDefaults
    OrdererType: kafka

    Addresses:
        - orderer1-service:7050
        - orderer2-service:7050
        - orderer3-service:7050

    BatchTimeout: 50ms

    BatchSize:

        MaxMessageCount: 1
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - kafka1-service:9092
            - kafka2-service:9092
            - kafka3-service:9092
            - kafka4-service:9092

    Organizations:


Application: &ApplicationDefaults
    Organizations:

Capabilities:

    Global: &ChannelCapabilities
        V1_3: true

    Orderer: &OrdererCapabilities
        V1_3: true

    Application: &ApplicationCapabilities
        V1_3: true
