version: "3"

services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
