apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kafka3
  template:
    metadata:
      labels:
        component: kafka3
    spec:
      restartPolicy: Always
      containers:
        - name: kafka3
          image: hyperledger/fabric-kafka:0.4.14
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_MESSAGE_MAX_BYTES
              value: "103809024"
            - name: KAFKA_REPLICA_FETCH_MAX_BYTES
              value: "103809024"
            - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE
              value: "false"
            - name: KAFKA_BROKER_ID
              value: "3"
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "2"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zoo1-service:2181,zoo2-service:2181,zoo3-service:2181,zoo4-service:2181,zoo5-service:2181"