OrdererOrgs:
  - Name: Orderer
    Domain: segfault.com
    Specs:
      - Hostname: orderer
    Template:
      Count: 3
PeerOrgs:
  - Name: Org1
    Domain: Org1.com
    EnableNodeOUs: true
    Template:
      Count: 3
    Users:
      Count: 1
  - Name: Org2
    Domain: Org2.com
    EnableNodeOUs: true
    Template:
      Count: 3
    Users:
      Count: 1
  - Name: Org3
    Domain: Org3.com
    EnableNodeOUs: true
    Template:
      Count: 3
    Users:
      Count: 1