apiVersion: v1
kind: Service
metadata:
  name: zoo2-service
spec:
  type: ClusterIP
  selector:
    component: zoo2
  ports:
    - port: 2181
      targetPort: 2181
      name: "operating"
    - port: 2888
      targetPort: 2888
      name: "service"
    - port: 3888
      targetPort: 3888
      name: "transmission"
